package com.example.csis3275.config;

import com.example.csis3275.entities.Experience;
import com.example.csis3275.entities.ExperienceInstance;
import com.example.csis3275.entities.User;
import com.example.csis3275.repositories.ExperienceRepository;
import com.example.csis3275.repositories.ExperienceInstanceRepository;
import com.example.csis3275.repositories.UserRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Component
public class ExperienceInitializer {

    @Autowired
    private ExperienceRepository experienceRepository;

    @Autowired
    private ExperienceInstanceRepository experienceInstanceRepository;

    @Autowired
    private UserRepository userRepository;

    @PostConstruct
    public void initData() {
        if (experienceRepository.count() == 0) {
            createInitialExperiences();
        }
    }

    //Generated by Claude Sonnet 4 
    private void createInitialExperiences() {
        // Get the first available user to assign experiences to
        Optional<User> userOptional = userRepository.findAll().stream().findFirst();
        if (userOptional.isEmpty()) {
            System.out.println("⚠️ No users found. Cannot create experiences without a user.");
            return;
        }
        
        User user = userOptional.get();
        System.out.println("🎯 Creating experiences for user: " + user.getUsername());

        // Create Experience 1: Walking through English Bay
        Experience experience1 = new Experience();
        experience1.setTitle("Walking through English Bay");
        experience1.setDescription("Enjoy a peaceful walk along the beautiful English Bay waterfront. Experience stunning sunset views, street performers, and the vibrant beach atmosphere.");
        experience1.setShortDescription("Scenic waterfront walk with sunset views");
        experience1.setCountry("Canada");
        experience1.setCity("Vancouver");
        experience1.setLocation("English Bay Beach, Vancouver, BC");
        experience1.setMaxParticipants(15);
        experience1.setPrice(25.00);
        experience1.setUser(user);
        experience1.setInstances(new ArrayList<>());
        experienceRepository.save(experience1);

        // Create instances for Experience 1
        createInstancesForExperience(experience1, 25.00);

        // Create Experience 2: Stanley Park Nature Tour
        Experience experience2 = new Experience();
        experience2.setTitle("Stanley Park Nature Tour");
        experience2.setDescription("Explore Vancouver's crown jewel - Stanley Park. Discover ancient forests, scenic seawall, totem poles, and learn about local wildlife and history.");
        experience2.setShortDescription("Guided tour through Stanley Park's highlights");
        experience2.setCountry("Canada");
        experience2.setCity("Vancouver");
        experience2.setLocation("Stanley Park, Vancouver, BC");
        experience2.setMaxParticipants(20);
        experience2.setPrice(35.00);
        experience2.setUser(user);
        experience2.setInstances(new ArrayList<>());
        experienceRepository.save(experience2);

        // Create instances for Experience 2
        createInstancesForExperience(experience2, 35.00);

        // Create Experience 3: Granville Island Food Tour
        Experience experience3 = new Experience();
        experience3.setTitle("Granville Island Food Tour");
        experience3.setDescription("Taste your way through Granville Island Public Market and local eateries. Sample artisanal foods, fresh seafood, and local delicacies while learning about Vancouver's culinary scene.");
        experience3.setShortDescription("Culinary adventure through Granville Island");
        experience3.setCountry("Canada");
        experience3.setCity("Vancouver");
        experience3.setLocation("Granville Island, Vancouver, BC");
        experience3.setMaxParticipants(12);
        experience3.setPrice(55.00);
        experience3.setUser(user);
        experience3.setInstances(new ArrayList<>());
        experienceRepository.save(experience3);

        // Create instances for Experience 3
        createInstancesForExperience(experience3, 55.00);

        System.out.println("✅ Created 3 experiences with 3 instances each!");
        System.out.println("📅 Experiences scheduled for upcoming dates and times");
    }

    private void createInstancesForExperience(Experience experience, double price) {
        LocalDateTime baseTime = LocalDateTime.now().plusDays(3); // Start 3 days from now

        // Instance 1: Friday at 7:00 PM
        ExperienceInstance instance1 = new ExperienceInstance();
        instance1.setExperience(experience);
        instance1.setStartTime(baseTime.withHour(19).withMinute(0).withSecond(0)); // 7:00 PM
        instance1.setEndTime(instance1.getStartTime().plusHours(2)); // 2 hours duration
        instance1.setAvailableSlots(experience.getMaxParticipants());
        instance1.setPrice(price);
        experienceInstanceRepository.save(instance1);

        // Instance 2: Saturday at 7:00 PM
        ExperienceInstance instance2 = new ExperienceInstance();
        instance2.setExperience(experience);
        instance2.setStartTime(baseTime.plusDays(1).withHour(19).withMinute(0).withSecond(0)); // Next day, 7:00 PM
        instance2.setEndTime(instance2.getStartTime().plusHours(2));
        instance2.setAvailableSlots(experience.getMaxParticipants());
        instance2.setPrice(price);
        experienceInstanceRepository.save(instance2);

        // Instance 3: Sunday at 2:00 PM (afternoon option)
        ExperienceInstance instance3 = new ExperienceInstance();
        instance3.setExperience(experience);
        instance3.setStartTime(baseTime.plusDays(2).withHour(14).withMinute(0).withSecond(0)); // 2:00 PM
        instance3.setEndTime(instance3.getStartTime().plusHours(2));
        instance3.setAvailableSlots(experience.getMaxParticipants());
        instance3.setPrice(price);
        experienceInstanceRepository.save(instance3);

        // Add instances to experience
        List<ExperienceInstance> instances = new ArrayList<>();
        instances.add(instance1);
        instances.add(instance2);
        instances.add(instance3);
        experience.setInstances(instances);
        experienceRepository.save(experience);
    }
}
