spring.application.name = csis3275
server.port=8882
spring.datasource.url= jdbc:mysql://localhost:3306/jwdm?createDatabaseIfNotExists=true
spring.datasource.username=root
spring.datasource.password=Nike12#$
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

# JWT Configuration
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=86400000

# Logging Configuration
logging.level.com.example.csis3275=DEBUG
logging.level.com.example.csis3275.controllers.UserController=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n